# Config
version: '1'
database:
  host: "localhost"
  port: 3306
  name: foxmanga
  user: hieppp
  password: 123456
redis:
  host: xxx
  port: xxx
  name: database_name
  user: xx
  password: xxx
domain:
  host: xxx
  port: xxx